// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIFZuj7Vj1Sug4UTQTmZfKp3ajuYEo_iM',
    appId: '1:200837377286:web:20cb933495ec5f545c0287',
    messagingSenderId: '200837377286',
    projectId: 'emart-c8d01',
    authDomain: 'emart-c8d01.firebaseapp.com',
    storageBucket: 'emart-c8d01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAviMNBrBJWBP_NxNF0O5BtcXM78XC6GFk',
    appId: '1:200837377286:android:79b7d518797e7a0d5c0287',
    messagingSenderId: '200837377286',
    projectId: 'emart-c8d01',
    storageBucket: 'emart-c8d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Ia_z4TezMpnlhP7AwycqzzmOtvv1TfQ',
    appId: '1:200837377286:ios:35dec21a1d2ee7a15c0287',
    messagingSenderId: '200837377286',
    projectId: 'emart-c8d01',
    storageBucket: 'emart-c8d01.appspot.com',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Ia_z4TezMpnlhP7AwycqzzmOtvv1TfQ',
    appId: '1:200837377286:ios:35dec21a1d2ee7a15c0287',
    messagingSenderId: '200837377286',
    projectId: 'emart-c8d01',
    storageBucket: 'emart-c8d01.appspot.com',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIFZuj7Vj1Sug4UTQTmZfKp3ajuYEo_iM',
    appId: '1:200837377286:web:7d1dbd85746ddde55c0287',
    messagingSenderId: '200837377286',
    projectId: 'emart-c8d01',
    authDomain: 'emart-c8d01.firebaseapp.com',
    storageBucket: 'emart-c8d01.appspot.com',
  );
}
